CONTIKI = ../..
CONTIKI_PROJECT = drone sink relay jammer \
	attacker_replay attacker_flood attacker_spoof attacker_impersonation \
	relay_blackhole relay_selective
CONTIKI_WITH_RIME = 1
CONTIKI_WITH_IPV6 = 0
all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
